export type FeatureModuleId =
  | "prediction"
  | "maps"
  | "emergency"
  | "assistant"
  | "healthcare"
  | "agriculture"
  | "vision"
  | "dashboard"
  | "community"
  | "platform"
  | "extras";

export type Feature = {
  id: number;
  name: string;
  description: string;
  howItWorks: string;
  module: FeatureModuleId;
};

export type ModuleInfo = {
  id: FeatureModuleId;
  title: string;
  subtitle: string;
  href: string;
  count: number;
};

export const modules: ModuleInfo[] = [
  {
    id: "prediction",
    title: "AI Disaster Prediction",
    subtitle: "Multi-hazard risk before disaster hits",
    href: "/prediction",
    count: 8,
  },
  {
    id: "maps",
    title: "Smart Maps & Navigation",
    subtitle: "Live zones, safe routes, shelters, hospitals",
    href: "/map",
    count: 9,
  },
  {
    id: "emergency",
    title: "Emergency Response",
    subtitle: "Alerts, live location, offline emergency mode",
    href: "/emergency",
    count: 7,
  },
  {
    id: "assistant",
    title: "AI Emergency Assistant",
    subtitle: "One multilingual assistant for everything",
    href: "/assistant",
    count: 7,
  },
  {
    id: "healthcare",
    title: "Healthcare Support",
    subtitle: "First aid, hospitals, ambulance, outbreak risk",
    href: "/healthcare",
    count: 7,
  },
  {
    id: "agriculture",
    title: "Agriculture Recovery",
    subtitle: "Crop damage, insurance, compensation guidance",
    href: "/agriculture",
    count: 6,
  },
  {
    id: "vision",
    title: "Computer Vision Analysis",
    subtitle: "Damage detection from uploaded images",
    href: "/vision",
    count: 6,
  },
  {
    id: "dashboard",
    title: "Govt & Rescue Dashboard",
    subtitle: "Live monitoring and resource allocation",
    href: "/dashboard",
    count: 7,
  },
  {
    id: "community",
    title: "Community Features",
    subtitle: "Reports, volunteers, verified alerts",
    href: "/community",
    count: 6,
  },
  {
    id: "platform",
    title: "Smart Platform Features",
    subtitle: "Offline, languages, roles, analytics",
    href: "/platform",
    count: 7,
  },
  {
    id: "extras",
    title: "Extra Unique Features",
    subtitle: "WhatsApp bot, reunion board, fake-news filter",
    href: "/extras",
    count: 12,
  },
];

export const features: Feature[] = [
  {
    id: 1,
    name: "AI Flood Prediction",
    description: "Estimates flood probability for a region.",
    howItWorks: "Uses rainfall, river and location signals to score flood risk.",
    module: "prediction",
  },
  {
    id: 2,
    name: "AI Cyclone Prediction",
    description: "Tracks cyclone risk zones and timing.",
    howItWorks: "Combines wind, pressure and track outlook into alerts.",
    module: "prediction",
  },
  {
    id: 3,
    name: "AI Landslide Prediction",
    description: "Flags landslide risk in hilly terrain.",
    howItWorks: "Rain intensity + slope/terrain factors create risk score.",
    module: "prediction",
  },
  {
    id: 4,
    name: "AI Earthquake Risk Analysis",
    description: "Relative earthquake vulnerability by zone.",
    howItWorks: "Seismic zone maps and historical patterns inform risk.",
    module: "prediction",
  },
  {
    id: 5,
    name: "AI Heatwave Prediction",
    description: "Predicts dangerous heat conditions.",
    howItWorks: "Temperature and humidity create heat-index alerts.",
    module: "prediction",
  },
  {
    id: 6,
    name: "AI Drought Prediction",
    description: "Estimates drought stress weeks ahead.",
    howItWorks: "Rainfall deficit and moisture trends drive the score.",
    module: "prediction",
  },
  {
    id: 7,
    name: "Real-time Weather Monitoring",
    description: "Live weather conditions for disaster regions.",
    howItWorks: "Polls weather APIs and shows current conditions.",
    module: "prediction",
  },
  {
    id: 8,
    name: "Disaster Risk Score",
    description: "Single 0–100 multi-hazard risk score.",
    howItWorks: "Weighted blend of all hazard models for one location.",
    module: "prediction",
  },
  {
    id: 9,
    name: "Live Disaster Map",
    description: "Active disaster layers on an interactive map.",
    howItWorks: "Overlays hazard polygons and incident markers.",
    module: "maps",
  },
  {
    id: 10,
    name: "Flood Zone Mapping",
    description: "Shows flooded and high-risk flood areas.",
    howItWorks: "Renders predicted/observed flood polygons.",
    module: "maps",
  },
  {
    id: 11,
    name: "Safe Zone Detection",
    description: "Highlights safer high-ground and shelter areas.",
    howItWorks: "Combines elevation, capacity and current risk.",
    module: "maps",
  },
  {
    id: 12,
    name: "Safe Route Navigation",
    description: "Suggests safest path during disaster.",
    howItWorks: "Routing avoids flooded and blocked roads.",
    module: "maps",
  },
  {
    id: 13,
    name: "Alternative Evacuation Routes",
    description: "Backup routes when primary path fails.",
    howItWorks: "Generates 2–3 alternate evacuation options.",
    module: "maps",
  },
  {
    id: 14,
    name: "Nearby Shelter Finder",
    description: "Finds nearest relief shelters.",
    howItWorks: "Geo-search by distance and occupancy.",
    module: "maps",
  },
  {
    id: 15,
    name: "Nearby Hospital Finder",
    description: "Finds nearest hospitals and clinics.",
    howItWorks: "Geo-search medical facilities with open status.",
    module: "maps",
  },
  {
    id: 16,
    name: "Blocked Road Detection",
    description: "Marks roads closed by flood or debris.",
    howItWorks: "Citizen reports + traffic/vision signals update map.",
    module: "maps",
  },
  {
    id: 17,
    name: "Live Traffic Monitoring During Disaster",
    description: "Shows traffic conditions in crisis zones.",
    howItWorks: "Traffic layers help choose evacuation corridors.",
    module: "maps",
  },
  {
    id: 18,
    name: "One-Tap Emergency Alert",
    description: "Sends urgent help request with location.",
    howItWorks: "Captures GPS, profile and emergency type instantly.",
    module: "emergency",
  },
  {
    id: 19,
    name: "Live Location Sharing",
    description: "Shares live GPS with family/rescue.",
    howItWorks: "Streams location for a chosen duration.",
    module: "emergency",
  },
  {
    id: 20,
    name: "Family Emergency Alerts",
    description: "Notifies saved family contacts.",
    howItWorks: "Push/SMS-style alerts to priority contacts.",
    module: "emergency",
  },
  {
    id: 21,
    name: "Emergency Contact Management",
    description: "Add and prioritize emergency contacts.",
    howItWorks: "User CRUD for contact list and order.",
    module: "emergency",
  },
  {
    id: 22,
    name: "Offline Emergency Mode",
    description: "Works with weak or no network.",
    howItWorks: "Caches maps, helplines and queues alerts for sync.",
    module: "emergency",
  },
  {
    id: 23,
    name: "Emergency Alert Notifications",
    description: "Pushes high-risk disaster alerts.",
    howItWorks: "Triggers when risk score crosses threshold.",
    module: "emergency",
  },
  {
    id: 24,
    name: "Safe Check-in Feature",
    description: "Lets users mark themselves safe.",
    howItWorks: "Publishes safe status to family/community board.",
    module: "emergency",
  },
  {
    id: 25,
    name: "Multilingual AI Chatbot",
    description: "Chat help in Indian languages.",
    howItWorks: "LLM replies in chosen language for disaster tasks.",
    module: "assistant",
  },
  {
    id: 26,
    name: "Voice Assistant",
    description: "Hands-free voice guidance.",
    howItWorks: "Mic → STT → assistant → TTS response.",
    module: "assistant",
  },
  {
    id: 27,
    name: "Speech-to-Text",
    description: "Converts speech to text.",
    howItWorks: "Supports Indian-language voice input.",
    module: "assistant",
  },
  {
    id: 28,
    name: "Text-to-Speech",
    description: "Reads guidance aloud.",
    howItWorks: "Useful for low-literacy and hands-free use.",
    module: "assistant",
  },
  {
    id: 29,
    name: "First Aid Guidance",
    description: "Step-by-step first aid help.",
    howItWorks: "Verified first-aid flows via assistant.",
    module: "assistant",
  },
  {
    id: 30,
    name: "Disaster Preparedness Guidance",
    description: "Pre-disaster readiness tips.",
    howItWorks: "Checklists by disaster type.",
    module: "assistant",
  },
  {
    id: 31,
    name: "Government Relief Scheme Assistant",
    description: "Explains schemes and apply steps.",
    howItWorks: "RAG-style guidance over relief schemes.",
    module: "assistant",
  },
  {
    id: 32,
    name: "AI First Aid Assistant",
    description: "Medical first-response guidance.",
    howItWorks: "Symptom/injury input → immediate steps.",
    module: "healthcare",
  },
  {
    id: 33,
    name: "Nearby Hospital & Clinic Finder",
    description: "Locate trauma and emergency care.",
    howItWorks: "Filters hospitals by distance and specialty.",
    module: "healthcare",
  },
  {
    id: 34,
    name: "Ambulance Tracking",
    description: "Track assigned ambulance status.",
    howItWorks: "Shows dispatch and live location updates.",
    module: "healthcare",
  },
  {
    id: 35,
    name: "Blood Bank Finder",
    description: "Find nearby blood banks.",
    howItWorks: "Lists banks with group availability updates.",
    module: "healthcare",
  },
  {
    id: 36,
    name: "Medicine Availability",
    description: "Check medicine stock nearby.",
    howItWorks: "Relief camp/pharmacy inventory lookup.",
    module: "healthcare",
  },
  {
    id: 37,
    name: "Disease Outbreak Prediction After Disaster",
    description: "Post-disaster disease risk warnings.",
    howItWorks: "Uses water, crowding and history signals.",
    module: "healthcare",
  },
  {
    id: 38,
    name: "Emergency Medical Information Card",
    description: "Offline medical ID card.",
    howItWorks: "Blood group, allergies, meds, contacts + QR.",
    module: "healthcare",
  },
  {
    id: 39,
    name: "AI Crop Damage Detection",
    description: "Detect crop loss from photos.",
    howItWorks: "CV model estimates damage percentage.",
    module: "agriculture",
  },
  {
    id: 40,
    name: "Farm Flood Assessment",
    description: "Estimates flooded farmland.",
    howItWorks: "Field location + flood layer analysis.",
    module: "agriculture",
  },
  {
    id: 41,
    name: "Crop Recovery Recommendations",
    description: "Replant and soil recovery tips.",
    howItWorks: "Advice based on crop, season and damage.",
    module: "agriculture",
  },
  {
    id: 42,
    name: "Livestock Safety Alerts",
    description: "Alerts to move animals to safety.",
    howItWorks: "Risk map triggers livestock relocation tips.",
    module: "agriculture",
  },
  {
    id: 43,
    name: "Insurance Claim Assistance",
    description: "Helps prepare crop insurance claims.",
    howItWorks: "Forms + photo evidence pack guidance.",
    module: "agriculture",
  },
  {
    id: 44,
    name: "Government Compensation Guidance",
    description: "Guides compensation applications.",
    howItWorks: "Docs and process by state relief norms.",
    module: "agriculture",
  },
  {
    id: 45,
    name: "Flood Detection from Images",
    description: "Classifies flood severity from photos.",
    howItWorks: "Vision model labels flooded/not/severity.",
    module: "vision",
  },
  {
    id: 46,
    name: "Building Damage Detection",
    description: "Detects damaged buildings from images.",
    howItWorks: "CV finds collapse/crack indicators.",
    module: "vision",
  },
  {
    id: 47,
    name: "Road Damage Detection",
    description: "Detects washouts and road breaks.",
    howItWorks: "Analyzes uploaded road photos.",
    module: "vision",
  },
  {
    id: 48,
    name: "Bridge Damage Detection",
    description: "Flags bridge structural damage cues.",
    howItWorks: "Vision analysis of bridge images.",
    module: "vision",
  },
  {
    id: 49,
    name: "Aerial Image Damage Assessment",
    description: "Area damage from aerial uploads.",
    howItWorks: "Processes drone/aerial frames into heatmaps.",
    module: "vision",
  },
  {
    id: 50,
    name: "Infrastructure Damage Analysis",
    description: "Aggregated damage report for officials.",
    howItWorks: "Combines CV outputs into district reports.",
    module: "vision",
  },
  {
    id: 51,
    name: "Live Disaster Monitoring",
    description: "Command-center live situation view.",
    howItWorks: "Incidents, risk and teams on one dashboard.",
    module: "dashboard",
  },
  {
    id: 52,
    name: "Rescue Team Tracking",
    description: "Track rescue teams in the field.",
    howItWorks: "Team GPS and task status updates.",
    module: "dashboard",
  },
  {
    id: 53,
    name: "Resource Allocation",
    description: "Allocate food, water, medicine, boats.",
    howItWorks: "Assigns resources by shortage score.",
    module: "dashboard",
  },
  {
    id: 54,
    name: "Shelter Occupancy Monitoring",
    description: "Live shelter capacity tracking.",
    howItWorks: "Check-in/out updates occupancy.",
    module: "dashboard",
  },
  {
    id: 55,
    name: "Food & Water Distribution Monitoring",
    description: "Tracks relief distribution.",
    howItWorks: "Stock in/out logs per camp.",
    module: "dashboard",
  },
  {
    id: 56,
    name: "Medical Supply Tracking",
    description: "Tracks medical inventory.",
    howItWorks: "Kits, oxygen, ORS and related stock.",
    module: "dashboard",
  },
  {
    id: 57,
    name: "Volunteer Management",
    description: "Register and assign volunteers.",
    howItWorks: "Verify volunteers and assign tasks.",
    module: "dashboard",
  },
  {
    id: 58,
    name: "Citizen Incident Reporting",
    description: "Report local disaster incidents.",
    howItWorks: "Form + GPS + incident type submission.",
    module: "community",
  },
  {
    id: 59,
    name: "Photo & Video Evidence Upload",
    description: "Attach media proof to reports.",
    howItWorks: "Uploads linked to incident records.",
    module: "community",
  },
  {
    id: 60,
    name: "Missing Person Reporting",
    description: "Report and search missing people.",
    howItWorks: "Board with report/search/match alerts.",
    module: "community",
  },
  {
    id: 61,
    name: "Volunteer Coordination",
    description: "Coordinate local volunteer help.",
    howItWorks: "Join nearby tasks and update status.",
    module: "community",
  },
  {
    id: 62,
    name: "Community Safe Check-In",
    description: "Area-wise safe people feed.",
    howItWorks: "Community feed of safe check-ins.",
    module: "community",
  },
  {
    id: 63,
    name: "Verified Community Alerts",
    description: "Shows only verified local alerts.",
    howItWorks: "Admin/verified reporters publish trusted alerts.",
    module: "community",
  },
  {
    id: 64,
    name: "Offline Maps",
    description: "Download maps for offline use.",
    howItWorks: "Caches region tiles for offline navigation.",
    module: "platform",
  },
  {
    id: 65,
    name: "Offline Emergency Information",
    description: "Cached first-aid and helplines.",
    howItWorks: "Stores critical info for offline access.",
    module: "platform",
  },
  {
    id: 66,
    name: "Multi-Language Support",
    description: "Indian language UI and AI replies.",
    howItWorks: "i18n UI + multilingual assistant output.",
    module: "platform",
  },
  {
    id: 67,
    name: "AI Risk Analytics Dashboard",
    description: "Charts for risk and response trends.",
    howItWorks: "Analytics on risk, alerts and damage.",
    module: "platform",
  },
  {
    id: 68,
    name: "Secure Cloud Data Backup",
    description: "Encrypted backup of critical data.",
    howItWorks: "Cloud backup for user/govt records.",
    module: "platform",
  },
  {
    id: 69,
    name: "Emergency Notification System",
    description: "Multi-channel alert delivery.",
    howItWorks: "Push/SMS/email fanout engine.",
    module: "platform",
  },
  {
    id: 70,
    name: "Role-Based Access",
    description: "Citizen, Rescue, Government roles.",
    howItWorks: "RBAC controls screens and permissions.",
    module: "platform",
  },
  {
    id: 71,
    name: "Early Warning Siren Mode",
    description: "Loud alarm on critical risk.",
    howItWorks: "Overrides silent mode for high alerts.",
    module: "extras",
  },
  {
    id: 72,
    name: "WhatsApp Alert Bot",
    description: "Disaster help over WhatsApp.",
    howItWorks: "Bot sends alerts and guidance via WhatsApp.",
    module: "extras",
  },
  {
    id: 73,
    name: "Helpline Directory",
    description: "112, NDRF and local helplines.",
    howItWorks: "District-wise emergency number directory.",
    module: "extras",
  },
  {
    id: 74,
    name: "Boat / Rescue Asset Finder",
    description: "Find boats, pumps and rescue assets.",
    howItWorks: "Tracks available rescue assets by zone.",
    module: "extras",
  },
  {
    id: 75,
    name: "Evacuation Center QR Check-in",
    description: "QR-based shelter check-in.",
    howItWorks: "Scan updates occupancy automatically.",
    module: "extras",
  },
  {
    id: 76,
    name: "Family Reunion Board",
    description: "Reconnect separated families.",
    howItWorks: "Lost-and-found matching board.",
    module: "extras",
  },
  {
    id: 77,
    name: "Women / Child Safety Priority Support",
    description: "Priority handling for vulnerable users.",
    howItWorks: "Priority queue tagging in response workflows.",
    module: "extras",
  },
  {
    id: 78,
    name: "Power Outage Map",
    description: "Shows electricity-down zones.",
    howItWorks: "Citizen/admin outage reports on map.",
    module: "extras",
  },
  {
    id: 79,
    name: "Clean Water Point Map",
    description: "Safe drinking water points after floods.",
    howItWorks: "Maps verified clean-water locations.",
    module: "extras",
  },
  {
    id: 80,
    name: "Post-Disaster Mental Health Support",
    description: "Counselling prompts and helplines.",
    howItWorks: "Multilingual mental-health guidance flows.",
    module: "extras",
  },
  {
    id: 81,
    name: "Fake News / Panic Post Filter",
    description: "Flags unverified panic content.",
    howItWorks: "AI checks before community publish.",
    module: "extras",
  },
  {
    id: 82,
    name: "Govt Action Audit Logs",
    description: "Transparent record of relief actions.",
    howItWorks: "Logs who allocated what and when.",
    module: "extras",
  },
];

export function featuresByModule(module: FeatureModuleId) {
  return features.filter((f) => f.module === module);
}

export const TOTAL_FEATURES = features.length;
