import PDFDocument from "pdfkit";
import type { InvestigationReport } from "./report-generator";

function sectionText(content: string | Record<string, unknown> | unknown[]): string {
  if (typeof content === "string") return content;
  return JSON.stringify(content, null, 2);
}

export function renderReportPdf(report: InvestigationReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).font("Helvetica-Bold").text("Bharat Raksha AI", { align: "center" });
    doc.fontSize(14).text("SIH26190 Legal & Investigation Document Report", { align: "center" });
    doc.moveDown();

    doc.fontSize(10).font("Helvetica").fillColor("#666666");
    doc.text(report.meta.classification, { align: "center" });
    doc.fillColor("#000000");
    doc.moveDown();

    doc.fontSize(12).font("Helvetica-Bold").text(`Case: ${report.meta.caseNumber}`);
    doc.font("Helvetica").fontSize(10);
    doc.text(`Crime Type: ${report.meta.crimeType}`);
    doc.text(`Status: ${report.meta.status} | Priority: ${report.meta.priority}`);
    if (report.meta.location) doc.text(`Location: ${report.meta.location}`);
    doc.text(`Generated: ${new Date(report.meta.generatedAt).toLocaleString("en-IN")}`);
    doc.text(`Officer: ${report.meta.generatedBy}`);
    doc.moveDown();

    doc.font("Helvetica-Bold").text("Summary Counts");
    doc.font("Helvetica");
    doc.text(
      `Entities: ${report.summary.entityCount} | Evidence: ${report.summary.evidenceCount} | Alerts: ${report.summary.alertCount} | CDR: ${report.summary.cdrCount} | Transactions: ${report.summary.transactionCount}`
    );
    doc.moveDown();

    for (const section of report.sections) {
      if (doc.y > 700) doc.addPage();
      doc.font("Helvetica-Bold").fontSize(11).text(section.title);
      doc.font("Helvetica").fontSize(9).moveDown(0.3);
      const text = sectionText(section.content);
      const lines = text.match(/.{1,95}(\s|$)/g) ?? [text];
      for (const line of lines.slice(0, 80)) {
        if (doc.y > 750) doc.addPage();
        doc.text(line.trim());
      }
      doc.moveDown();
    }

    if (doc.y > 650) doc.addPage();
    doc.font("Helvetica-Bold").fontSize(11).text("Evidence Integrity (SHA-256)");
    doc.font("Helvetica").fontSize(8);
    for (const src of report.sources.slice(0, 30)) {
      if (doc.y > 750) doc.addPage();
      doc.text(`${src.fileName} [${src.type}] — ${src.hash?.slice(0, 32)}...`);
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor("#666666");
    doc.text(
      "DISCLAIMER: Investigative leads only. Review recommended. Not proof of criminality. Generated by Bharat Raksha AI (SIH26190).",
      { align: "center" }
    );

    doc.end();
  });
}
