/**
 * Every capability in Bharat Raksha AI maps to SIH26190 (MHA · Smart Automation).
 * There is no second problem statement in product metadata.
 */
export const SIH26190_REGISTRY_META = {
  psAlignment: "SIH26190",
  ministry: "MHA",
  theme: "Smart Automation",
  title: "Secure Digital Document Management for Legal & Investigation Documents",
  onlyProblemStatement: true as const,
} as const;

export type Sih26190FeatureTier = "core" | "smart_automation" | "smart_automation_plus";

/** Maps registry id → how it supports SIH26190 (for judges / capabilities API). */
export const SIH26190_FEATURE_TIERS: Record<Sih26190FeatureTier, readonly string[]> = {
  core: [
    "register",
    "seed",
    "classify",
    "workflow",
    "io_cert",
    "prosecution_cert",
    "dual_seal",
    "hold",
    "version",
    "custody",
    "forward",
    "verify",
    "bsa63",
    "qr",
    "public",
    "register_export",
    "disclosure",
    "readiness",
    "court_prep",
    "timeline",
    "search",
    "retention",
    "stats",
    "download",
    "court_pack",
    "pending",
    "bulk_review",
    "compliance_pdf",
    "master_index",
    "alerts",
    "command",
    "templates",
  ],
  smart_automation: [
    "retention_scan",
    "audit_export",
    "ocr",
    "link",
    "auto_review",
    "auto_tags",
    "hi_ui",
    "playbooks",
    "one_click_court",
    "daily_autopilot",
    "reliability",
    "dupes",
    "court_manifest",
    "caption_ai",
    "webhook",
    "custody_timeline",
    "custody_transfer_dual",
    "custody_report",
  ],
  smart_automation_plus: [
    "ext_network",
    "ext_copilot",
    "ext_conflicts",
    "ext_cyber",
  ],
};

export function getSih26190FeatureTier(featureId: string): Sih26190FeatureTier {
  for (const tier of ["core", "smart_automation", "smart_automation_plus"] as const) {
    if ((SIH26190_FEATURE_TIERS[tier] as readonly string[]).includes(featureId)) return tier;
  }
  return "core";
}

/** Complete SIH26190 capability registry — each entry maps to a live API or page. */
export const SIH26190_FEATURE_REGISTRY = [
  { id: "register", label: "Document register (SIH26190)", route: "POST /api/cases/:id/ingest", page: "/legal-docs" },
  { id: "seed", label: "Register sample FIR pack", route: "POST .../legal-documents/seed-samples", page: "/legal-docs" },
  { id: "classify", label: "Smart filename classifier", route: "ingest (auto)", page: "/legal-docs" },
  { id: "workflow", label: "Legal status workflow", route: "PATCH .../legal-documents", page: "/legal-docs" },
  { id: "io_cert", label: "IO certification", route: "POST .../certify {lane:IO}", page: "/legal-docs" },
  { id: "prosecution_cert", label: "Prosecution certification", route: "POST .../certify {lane:PROSECUTION}", page: "/legal-docs" },
  { id: "dual_seal", label: "Electronic seal (dual cert)", route: "PATCH → SEALED", page: "/legal-docs" },
  { id: "hold", label: "Legal hold", route: "PATCH legalHold", page: "/legal-docs" },
  { id: "version", label: "Document versioning", route: "ingest parentEvidenceId", page: "/legal-docs" },
  { id: "custody", label: "Custody trail", route: "GET .../[evidenceId]", page: "/legal-docs" },
  { id: "forward", label: "Nazarat forwarding", route: "POST .../forward", page: "/legal-docs" },
  { id: "verify", label: "Bundle integrity verify", route: "POST .../verify", page: "/legal-docs" },
  { id: "bsa63", label: "BSA §63 certificate", route: "GET .../bsa/:id", page: "/legal-docs" },
  { id: "qr", label: "Nazarat QR sticker", route: "GET .../qr", page: "/legal-docs" },
  { id: "public", label: "Public verify portal", route: "GET /api/legal-documents/public-verify", page: "/verify-document" },
  { id: "register_export", label: "Register JSON/HTML", route: "GET .../register", page: "/legal-docs" },
  { id: "disclosure", label: "Disclosure annexure", route: "GET .../disclosure-schedule", page: "/legal-docs" },
  { id: "readiness", label: "Court readiness score", route: "GET .../readiness", page: "/legal-docs" },
  { id: "court_prep", label: "Court prep pack", route: "POST .../court-prep", page: "/legal-docs" },
  { id: "timeline", label: "Legal activity timeline", route: "GET .../timeline", page: "/legal-docs" },
  { id: "search", label: "Cross-case search", route: "GET /api/legal-documents/search", page: "/legal-docs" },
  { id: "retention", label: "Retention watchdog", route: "GET /api/legal-documents/retention-watch", page: "/legal-docs" },
  { id: "stats", label: "Org legal stats", route: "GET /api/legal-documents/stats", page: "/dashboard" },
  { id: "download", label: "Secure file download", route: "GET /api/evidence/:id/download", page: "/legal-docs" },
  { id: "court_pack", label: "Court pack manifest", route: "court pack API", page: "/court" },
  { id: "pending", label: "Pending review queue", route: "GET .../pending-review", page: "/legal-docs" },
  { id: "bulk_review", label: "Bulk send to review", route: "POST .../bulk-review", page: "/legal-docs" },
  { id: "compliance_pdf", label: "Compliance PDF report", route: "GET .../compliance-report", page: "/legal-docs" },
  { id: "master_index", label: "Master index CSV", route: "GET .../master-index", page: "/legal-docs" },
  { id: "alerts", label: "Legal document alerts", route: "Alert on register", page: "/alerts" },
  { id: "command", label: "MHA command center analytics", route: "GET /api/legal-documents/command-center", page: "/legal-command" },
  { id: "retention_scan", label: "Smart retention scan", route: "POST command-center", page: "/legal-command" },
  { id: "audit_export", label: "Legal audit bundle export", route: "GET .../audit-export", page: "/legal-docs" },
  { id: "templates", label: "FIR / 161 / seizure templates", route: "GET .../templates", page: "/legal-docs" },
  { id: "ocr", label: "OCR text excerpt (Smart Automation)", route: "GET .../ocr-excerpt", page: "/legal-docs" },
  { id: "link", label: "Related document linking", route: "PATCH linkDocumentId", page: "/legal-docs" },
  { id: "auto_review", label: "Auto queue FIR/statements", route: "ingest → UNDER_REVIEW", page: "/legal-docs" },
  { id: "auto_tags", label: "Post-ingest legal tags", route: "legal-automation enrich", page: "/legal-docs" },
  { id: "hi_ui", label: "Hindi UI labels", route: "legal-i18n", page: "/legal-docs" },
  { id: "playbooks", label: "Smart Automation playbooks", route: "GET /api/legal-documents/automation/playbooks", page: "/legal-command" },
  { id: "one_click_court", label: "One-Click MHA Court File", route: "POST .../automation/run", page: "/legal-docs" },
  { id: "daily_autopilot", label: "Org daily compliance autopilot", route: "POST /api/legal-documents/automation/daily-run", page: "/legal-command" },
  { id: "reliability", label: "Platform reliability score", route: "GET /api/legal-documents/reliability", page: "/legal-command" },
  { id: "dupes", label: "Duplicate hash watchdog", route: "GET .../duplicates", page: "/legal-docs" },
  { id: "court_manifest", label: "Court bundle manifest (JSON)", route: "GET .../court-bundle-manifest", page: "/legal-docs" },
  { id: "caption_ai", label: "Smart caption suggest (OCR)", route: "GET .../suggest-caption", page: "/legal-docs" },
  { id: "webhook", label: "Automation webhook audit", route: "LEGAL_AUTOMATION_WEBHOOK_URL", page: "/legal-command" },
  { id: "ext_network", label: "Smart Automation+ · Network graph", route: "/network", page: "/network" },
  { id: "ext_copilot", label: "Smart Automation+ · AI copilot", route: "/copilot", page: "/copilot" },
  { id: "ext_conflicts", label: "Smart Automation+ · Conflict radar", route: "/conflicts", page: "/conflicts" },
  { id: "ext_cyber", label: "Smart Automation+ · Cyber center", route: "/cyber", page: "/cyber" },
  { id: "custody_timeline", label: "Verifiable custody timeline (SIH26190)", route: "GET .../custody-timeline", page: "/legal-docs" },
  { id: "custody_transfer_dual", label: "Dual-confirmed custody transfer", route: "POST .../transfer + confirm", page: "/legal-docs" },
  { id: "custody_report", label: "Exportable custody report (HTML)", route: ".../custody-timeline?format=html", page: "/legal-docs" },
].map((f) => ({
  ...f,
  tier: getSih26190FeatureTier(f.id),
  psAlignment: "SIH26190" as const,
}));
